apiVersion: v1
kind: Namespace
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/part-of: gateway-service
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
